In [ ]:
import pandas as pd
import numpy as np

In [ ]:
report = pd.read_excel('/content/level completion report.xlsx', sheet_name='level completion report')
report.shape

(3923, 13)

In [ ]:
credit = pd.read_excel('/content/student wise credits.xlsx', sheet_name='studWiseCredits')
credit.shape

(33449, 51)

In [ ]:
report_bs= report[report['level'] == 'Bs']
report_bs.shape

(143, 13)

In [ ]:
credit.columns

Index(['Unnamed: 0', 'student_email', 'BD', 'BP', 'DD', 'DP', 'FL', 'HM', 'SE',
       'BP_Tc', 'BD_Tc', 'HM_Tc', 'SE_Tc', 'BD_L4', 'BP_L4', 'DD_L4', 'DP_L4',
       'FL_L4', 'HM_L4', 'SE_L4', 'TotalCredits', 'FL_Min', 'DP_Min', 'DD_Min',
       'BP_Min', 'BD_Min', 'HM_Min', 'SE_Min', 'email', 'CoreCompleted',
       'BDCompleted', 'BPCompleted', 'Unnamed: 32', 'FLCompleted',
       'DDCompleted', 'DPCompleted', 'HMCompleted', 'SECompleted',
       'BP_min_adjusted', 'BP_min_L4', 'BP_L4_Completed', 'BSc_BPCompleted',
       'BD_min_adjusted', 'BD_min_L4', 'BD_L4_Completed', 'BSc_BDCompleted',
       'BSc_HMCompleted', 'BSc_Credit', 'BS_Credit', 'All_Bsc_Completed',
       'All_Bs_Completed'],
      dtype='object')

# bs

for all student mails in report_bs,
 - if credit.TotalCredits == sum(credit['BD', 'BP', 'DD', 'DP', 'FL', 'HM', 'SE', 'BP_Tc', 'BD_Tc', 'HM_Tc', 'SE_Tc'])
 - report_bs.All_Bsc_Completed == credit.All_Bsc_Completed
 - report_bs.All_Bs_Completed == credit.All_Bs_Completed
 - report_bs.DDCompleted == credit.DDCompleted
 - report_bs.DPCompleted == credit.DPCompleted
 - if credit.TotalCredits >= 142
 - if credit.FL == 32
 - if credit.DD == 27
 - if credit.DP == 27
 - if credit.BD >= 16
 - if credit.BP >= 16
 - if credit.HM >= 8

In [ ]:
import pandas as pd
import numpy as np

def check_bs(report_bs: pd.DataFrame, credit: pd.DataFrame) -> pd.DataFrame:

    df = report_bs.merge(credit, on="student_email", how="left", suffixes=("_report", "_credit"))

    results = []

    credit_sum_cols = [
        'BD', 'BP', 'DD', 'DP', 'FL', 'HM', 'SE',
        'BP_Tc', 'BD_Tc', 'HM_Tc', 'SE_Tc'
    ]

    for _, row in df.iterrows():
        failed_checks = []

        # check 1: TotalCredits sum match
        credit_sum = row[credit_sum_cols].sum(skipna=False)
        if row['TotalCredits'] != credit_sum:
            failed_checks.append("check_totalcredits_sum")

        # check 2: All_Bsc_Completed
        if row['All_Bsc_Completed_report'] != row['All_Bsc_Completed_credit']:
            failed_checks.append("check_all_bsc_completed")

        # check 3: All_Bs_Completed
        if row['All_Bs_Completed_report'] != row['All_Bs_Completed_credit']:
            failed_checks.append("check_all_bs_completed")

        # check 4: DDCompleted
        if row['DDCompleted_report'] != row['DDCompleted_credit']:
            failed_checks.append("check_dd_completed")

        # check 5: DPCompleted
        if row['DPCompleted_report'] != row['DPCompleted_credit']:
            failed_checks.append("check_dp_completed")

        # check 6: TotalCredits >= 142
        if row['TotalCredits'] < 142:
            failed_checks.append("check_totalcredits_142")

        # check 7: FL == 32
        if row['FL'] != 32:
            failed_checks.append("check_fl_32")

        # check 8: DD == 27
        #if row['DD'] != 27:
        if not (
          (row['DD'] == 27) or
          (row['DD'] == 25 and row['DDCompleted_credit'] is True) or
          (row['DD'] == 23 and row['DDCompleted_credit'] is True)):
            failed_checks.append("check_dd_27")

        # check 9: DP == 27
        #if row['DP'] != 27:
            #failed_checks.append("check_dp_27")
        if not (
          (row['DP'] == 27) or
          (row['DP'] == 25 and row['DPCompleted_credit'] is True) or
          (row['DP'] == 23 and row['DPCompleted_credit'] is True)):
            failed_checks.append("check_dp_27")

        # check 10: BD >= 16
        if (row['BD'] + row['BD_Tc']) < 16:
            failed_checks.append("check_bd_16")

        # check 11: BP >= 16
        if (row['BP'] + row['BP_Tc']) < 16:
            failed_checks.append("check_bp_16")

        # check 12: HM >=8
        if (row['HM']+ row['HM_Tc']) < 8:
            failed_checks.append("check_hm_8")

        # check 13:

        # final status
        status = "yes" if not failed_checks else failed_checks

        results.append({
            "student_email": row["student_email"],
            "status": status
        })

    return pd.DataFrame(results)

In [ ]:
result= check_bs(report_bs, credit)

In [ ]:
result[result['status'] != 'yes'].shape

(3, 2)

In [ ]:
result[result['status'] != 'yes']

                      student_email         status
34         faizanamulla69@gmail.com  [check_bp_16]
113        sayan10rakshit@gmail.com  [check_bp_16]
132  21f1005136@ds.study.iitm.ac.in  [check_bp_16]

# Bse

In [ ]:
report_bsc= report[report['level'] == 'Bsc']
report_bsc.shape

(254, 13)

In [ ]:
def check_bsc(report_bs: pd.DataFrame, credit: pd.DataFrame) -> pd.DataFrame:

    df = report_bs.merge(credit, on="student_email", how="left", suffixes=("_report", "_credit"))

    results = []

    credit_sum_cols = [
        'BD', 'BP', 'DD', 'DP', 'FL', 'HM', 'SE',
        'BP_Tc', 'BD_Tc', 'HM_Tc', 'SE_Tc'
    ]

    for _, row in df.iterrows():
        failed_checks = []

        # check 1: TotalCredits sum match
        credit_sum = row[credit_sum_cols].sum(skipna=False)
        if row['TotalCredits'] != credit_sum:
            failed_checks.append("check_totalcredits_sum")

        # check 2: All_Bsc_Completed
        if row['All_Bsc_Completed_report'] != row['All_Bsc_Completed_credit']:
            failed_checks.append("check_all_bsc_completed")

        # check 3: All_Bs_Completed
        if row['All_Bs_Completed_report'] != row['All_Bs_Completed_credit']:
            failed_checks.append("check_all_bs_completed")

        # check 4: DDCompleted
        if row['DDCompleted_report'] != row['DDCompleted_credit']:
            failed_checks.append("check_dd_completed")

        # check 5: DPCompleted
        if row['DPCompleted_report'] != row['DPCompleted_credit']:
            failed_checks.append("check_dp_completed")

        # check 6: TotalCredits >= 114
        if row['TotalCredits'] < 114:
            failed_checks.append("check_totalcredits_114")

        # check 7: FL == 32
        if row['FL'] != 32:
            failed_checks.append("check_fl_32")

        # check 8: DD == 27
        #if row['DD'] != 27:
        if not (
          (row['DD'] == 27) or
          (row['DD'] == 25 and row['DDCompleted_credit'] is True) or
          (row['DD'] == 23 and row['DDCompleted_credit'] is True)):
            failed_checks.append("check_dd_27")

        # check 9: DP == 27
        #if row['DP'] != 27:
            #failed_checks.append("check_dp_27")
        if not (
          (row['DP'] == 27) or
          (row['DP'] == 25 and row['DPCompleted_credit'] is True) or
          (row['DP'] == 23 and row['DPCompleted_credit'] is True)):
            failed_checks.append("check_dp_27")

        # check 10: BD >= 8
        if (row['BD'] + row['BD_Tc']) < 8:
            failed_checks.append("check_bd_16")

        # check 11: BP >= 8
        if (row['BP'] + row['BP_Tc']) < 8:
            failed_checks.append("check_bp_16")

        # check 12: HM >=4
        if (row['HM']+ row['HM_Tc']) < 4:
            failed_checks.append("check_hm_8")

        # check 13:

        # final status
        status = "yes" if not failed_checks else failed_checks

        results.append({
            "student_email": row["student_email"],
            "status": status
        })

    return pd.DataFrame(results)

In [ ]:
result_bsc= check_bsc(report_bsc, credit)

In [ ]:
result_bsc[result_bsc['status'] != 'yes'].shape

(0, 2)

# DP

In [ ]:
report_dp= report[report['level'] == 'DP']
report_dp.shape

(609, 13)

In [ ]:
def check_dp(report_bs: pd.DataFrame, credit: pd.DataFrame) -> pd.DataFrame:

    df = report_bs.merge(credit, on="student_email", how="left", suffixes=("_report", "_credit"))

    results = []

    credit_sum_cols = [
        'BD', 'BP', 'DD', 'DP', 'FL', 'HM', 'SE',
        'BP_Tc', 'BD_Tc', 'HM_Tc', 'SE_Tc'
    ]

    for _, row in df.iterrows():
        failed_checks = []

        # check 1: TotalCredits sum match
        credit_sum = row[credit_sum_cols].sum(skipna=False)
        if row['TotalCredits'] != credit_sum:
            failed_checks.append("check_totalcredits_sum")

        # check 2: All_Bsc_Completed
        if row['All_Bsc_Completed_report'] != row['All_Bsc_Completed_credit']:
            failed_checks.append("check_all_bsc_completed")

        # check 3: All_Bs_Completed
        if row['All_Bs_Completed_report'] != row['All_Bs_Completed_credit']:
            failed_checks.append("check_all_bs_completed")

        # check 4: DDCompleted
        if row['DDCompleted_report'] != row['DDCompleted_credit']:
            failed_checks.append("check_dd_completed")

        # check 5: DPCompleted
        if row['DPCompleted_report'] != row['DPCompleted_credit']:
            failed_checks.append("check_dp_completed")

        # check 6: TotalCredits >= 114
        '''if not (
            (row['DDCompleted_report'] == True and row['TotalCredits'] == 86) or
            (row['DDCompleted_report'] == False and row['TotalCredits'] == 59)
        ):'''
        if not (row['TotalCredits'] <=114 and row['TotalCredits'] >=59):
            failed_checks.append("check_totalcredits_86_59")

        # check 7: FL == 32
        if row['FL'] != 32:
            failed_checks.append("check_fl_32")

        '''# check 8: DD == 27
        #if row['DD'] != 27:
        if not (
          (row['DD'] == 27) or
          (row['DD'] == 25 and row['DDCompleted_credit'] is True) or
          (row['DD'] == 23 and row['DDCompleted_credit'] is True)):
            failed_checks.append("check_dd_27")'''

        # check 9: DP == 27
        #if row['DP'] != 27:
            #failed_checks.append("check_dp_27")
        if not (
          (row['DP'] == 27) or
          (row['DP'] == 25 and row['DPCompleted_credit'] is True) or
          (row['DP'] == 23 and row['DPCompleted_credit'] is True)):
            failed_checks.append("check_dp_27")

        '''# check 10: BD >= 8
        if (row['BD'] + row['BD_Tc']) < 8:
            failed_checks.append("check_bd_16")

        # check 11: BP >= 8
        if (row['BP'] + row['BP_Tc']) < 8:
            failed_checks.append("check_bp_16")

        # check 12: HM >=4
        if (row['HM']+ row['HM_Tc']) < 4:
            failed_checks.append("check_hm_8")'''

        # check 13:

        # final status
        status = "yes" if not failed_checks else failed_checks

        results.append({
            "student_email": row["student_email"],
            "status": status
        })

    return pd.DataFrame(results)

In [ ]:
result_dp= check_dp(report_dp, credit)

In [ ]:
result_dp[result_dp['status'] != 'yes'].shape

(30, 2)

In [ ]:
result_dp[result_dp['status'] != 'yes']

                      student_email                      status
8    22f3002077@ds.study.iitm.ac.in  [check_totalcredits_86_59]
36   23f2000566@ds.study.iitm.ac.in  [check_totalcredits_86_59]
48   21f1004482@ds.study.iitm.ac.in  [check_totalcredits_86_59]
69   21f1005200@ds.study.iitm.ac.in  [check_totalcredits_86_59]
85   22f3000982@ds.study.iitm.ac.in  [check_totalcredits_86_59]
112  21f1004745@ds.study.iitm.ac.in  [check_totalcredits_86_59]
125  21f3001459@ds.study.iitm.ac.in  [check_totalcredits_86_59]
135  21f1001035@ds.study.iitm.ac.in  [check_totalcredits_86_59]
171  22f3001059@ds.study.iitm.ac.in  [check_totalcredits_86_59]
176  23f2000466@ds.study.iitm.ac.in  [check_totalcredits_86_59]
189  21f3002559@ds.study.iitm.ac.in  [check_totalcredits_86_59]
193  22f3002098@ds.study.iitm.ac.in  [check_totalcredits_86_59]
202  23f2004912@ds.study.iitm.ac.in  [check_totalcredits_86_59]
218  22f1000682@ds.study.iitm.ac.in  [check_totalcredits_86_59]
282  23f2004008@ds.study.iitm.ac.in  [check_totalcredits_86_59]
298  23f3001761@ds.study.iitm.ac.in  [check_totalcredits_86_59]
308  23f2002023@ds.study.iitm.ac.in  [check_totalcredits_86_59]
311  23f1000559@ds.study.iitm.ac.in  [check_totalcredits_86_59]
349  23f1001734@ds.study.iitm.ac.in  [check_totalcredits_86_59]
354  21f1006266@ds.study.iitm.ac.in  [check_totalcredits_86_59]
385  21f1003667@ds.study.iitm.ac.in  [check_totalcredits_86_59]
401  21f1002476@ds.study.iitm.ac.in  [check_totalcredits_86_59]
422  23f1001572@ds.study.iitm.ac.in  [check_totalcredits_86_59]
483  23f1003132@ds.study.iitm.ac.in  [check_totalcredits_86_59]
488  23f2003803@ds.study.iitm.ac.in  [check_totalcredits_86_59]
520  23f2004258@ds.study.iitm.ac.in  [check_totalcredits_86_59]
524  21f1006017@ds.study.iitm.ac.in  [check_totalcredits_86_59]
541  23f1000107@ds.study.iitm.ac.in  [check_totalcredits_86_59]
549  23f2005381@ds.study.iitm.ac.in  [check_totalcredits_86_59]
559  21f2001496@ds.study.iitm.ac.in  [check_totalcredits_86_59]

# DD

In [ ]:
report_dd= report[report['level'] == 'DD']
report_dd.shape

(519, 13)

In [ ]:
def check_dd(report_bs: pd.DataFrame, credit: pd.DataFrame) -> pd.DataFrame:

    df = report_bs.merge(credit, on="student_email", how="left", suffixes=("_report", "_credit"))

    results = []

    credit_sum_cols = [
        'BD', 'BP', 'DD', 'DP', 'FL', 'HM', 'SE',
        'BP_Tc', 'BD_Tc', 'HM_Tc', 'SE_Tc'
    ]

    for _, row in df.iterrows():
        failed_checks = []

        # check 1: TotalCredits sum match
        credit_sum = row[credit_sum_cols].sum(skipna=False)
        if row['TotalCredits'] != credit_sum:
            failed_checks.append("check_totalcredits_sum")

        # check 2: All_Bsc_Completed
        if row['All_Bsc_Completed_report'] != row['All_Bsc_Completed_credit']:
            failed_checks.append("check_all_bsc_completed")

        # check 3: All_Bs_Completed
        if row['All_Bs_Completed_report'] != row['All_Bs_Completed_credit']:
            failed_checks.append("check_all_bs_completed")

        # check 4: DDCompleted
        if row['DDCompleted_report'] != row['DDCompleted_credit']:
            failed_checks.append("check_dd_completed")

        # check 5: DPCompleted
        if row['DPCompleted_report'] != row['DPCompleted_credit']:
            failed_checks.append("check_dp_completed")

        # check 6: TotalCredits >= 114
        '''if not (
            (row['DDCompleted_report'] == True and row['TotalCredits'] == 86) or
            (row['DDCompleted_report'] == False and row['TotalCredits'] == 59)
        ):'''
        if not (row['TotalCredits'] <=114 and row['TotalCredits'] >=59):
            failed_checks.append("check_totalcredits_86_59")

        # check 7: FL == 32
        if row['FL'] != 32:
            failed_checks.append("check_fl_32")

        # check 8: DD == 27
        #if row['DD'] != 27:
        if not (
          (row['DD'] == 27) or
          (row['DD'] == 25 and row['DDCompleted_credit'] is True) or
          (row['DD'] == 23 and row['DDCompleted_credit'] is True)):
            failed_checks.append("check_dd_27")

        # check 9: DP == 27
        '''#if row['DP'] != 27:
            #failed_checks.append("check_dp_27")
        if not (
          (row['DP'] == 27) or
          (row['DP'] == 25 and row['DPCompleted_credit'] is True) or
          (row['DP'] == 23 and row['DPCompleted_credit'] is True)):
            failed_checks.append("check_dp_27")'''

        '''# check 10: BD >= 8
        if (row['BD'] + row['BD_Tc']) < 8:
            failed_checks.append("check_bd_16")

        # check 11: BP >= 8
        if (row['BP'] + row['BP_Tc']) < 8:
            failed_checks.append("check_bp_16")

        # check 12: HM >=4
        if (row['HM']+ row['HM_Tc']) < 4:
            failed_checks.append("check_hm_8")'''

        # check 13:

        # final status
        status = "yes" if not failed_checks else failed_checks

        results.append({
            "student_email": row["student_email"],
            "status": status
        })

    return pd.DataFrame(results)

In [ ]:
result_dd= check_dd(report_dd, credit)

In [ ]:
result_dd[result_dd['status'] != 'yes'].shape

(0, 2)

# FL

In [ ]:
report_fl= report[report['level'] == 'FL']
report_fl.shape

(2398, 13)

In [ ]:
def check_fl(report_bs: pd.DataFrame, credit: pd.DataFrame) -> pd.DataFrame:

    df = report_bs.merge(credit, on="student_email", how="left", suffixes=("_report", "_credit"))

    results = []

    credit_sum_cols = [
        'BD', 'BP', 'DD', 'DP', 'FL', 'HM', 'SE',
        'BP_Tc', 'BD_Tc', 'HM_Tc', 'SE_Tc'
    ]

    for _, row in df.iterrows():
        failed_checks = []

        # check 1: TotalCredits sum match
        credit_sum = row[credit_sum_cols].sum(skipna=False)
        if row['TotalCredits'] != credit_sum:
            failed_checks.append("check_totalcredits_sum")

        # check 2: All_Bsc_Completed
        if row['All_Bsc_Completed_report'] != row['All_Bsc_Completed_credit']:
            failed_checks.append("check_all_bsc_completed")

        # check 3: All_Bs_Completed
        if row['All_Bs_Completed_report'] != row['All_Bs_Completed_credit']:
            failed_checks.append("check_all_bs_completed")

        '''# check 4: DDCompleted
        if row['DDCompleted_report'] != row['DDCompleted_credit']:
            failed_checks.append("check_dd_completed")

        # check 5: DPCompleted
        if row['DPCompleted_report'] != row['DPCompleted_credit']:
            failed_checks.append("check_dp_completed")

        # check 6: TotalCredits >= 114
        if not (
            (row['DDCompleted_report'] == True and row['TotalCredits'] == 86) or
            (row['DDCompleted_report'] == False and row['TotalCredits'] == 59)
        ):'''

        if not (row['TotalCredits'] <59 and row['TotalCredits'] >=4):
        #if not (row['TotalCredits'] <=59 and row['TotalCredits'] >=32):
            failed_checks.append("check_totalcredits_59_32")


        '''# check 7: FL == 32
        if row['FL'] != 32:
            failed_checks.append("check_fl_32")

        # check 8: DD == 27
        #if row['DD'] != 27:
        if not (
          (row['DD'] == 27) or
          (row['DD'] == 25 and row['DDCompleted_credit'] is True) or
          (row['DD'] == 23 and row['DDCompleted_credit'] is True)):
            failed_checks.append("check_dd_27")

        # check 9: DP == 27
        #if row['DP'] != 27:
            #failed_checks.append("check_dp_27")
        if not (
          (row['DP'] == 27) or
          (row['DP'] == 25 and row['DPCompleted_credit'] is True) or
          (row['DP'] == 23 and row['DPCompleted_credit'] is True)):
            failed_checks.append("check_dp_27")'''

        '''# check 10: BD >= 8
        if (row['BD'] + row['BD_Tc']) < 8:
            failed_checks.append("check_bd_16")

        # check 11: BP >= 8
        if (row['BP'] + row['BP_Tc']) < 8:
            failed_checks.append("check_bp_16")

        # check 12: HM >=4
        if (row['HM']+ row['HM_Tc']) < 4:
            failed_checks.append("check_hm_8")'''

        # check 13:

        # final status
        status = "yes" if not failed_checks else failed_checks

        results.append({
            "student_email": row["student_email"],
            "status": status
        })

    return pd.DataFrame(results)

In [ ]:
result_fl= check_fl(report_fl, credit)

In [ ]:
result_fl[result_fl['status'] != 'yes'].shape

(0, 2)

In [ ]:
result_fl.tail()

                       student_email status
2393  25f2007091@ds.study.iitm.ac.in    yes
2394  24f3001537@ds.study.iitm.ac.in    yes
2395  24f3002569@ds.study.iitm.ac.in    yes
2396  25f2005287@ds.study.iitm.ac.in    yes
2397  25f1001574@ds.study.iitm.ac.in    yes

In [ ]:
result_fl[result_fl['student_email'] == '25f2000532@ds.study.iitm.ac.in']
#

Empty DataFrame
Columns: [student_email, status]
Index: []